name: CI Pipeline  # The name of the workflow

on:
  push:
    branches:
      - main   # Run CI when pushing to the main branch
  pull_request:
    branches:
      - main   # Run CI when a pull request is created for the main branch

jobs:
  test:  
    runs-on: ubuntu-latest  # The operating system where the workflow will run

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Gets the latest code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specifies Python version for running tests

    - name: Install dependencies
      run: |
        pip install pytest  # Install pytest

    - name: Run Unit Tests
      run: |
        pytest tests/  # Run all tests inside the 'tests' directory
